# Naive Bayes - Mashroom dataset
- Goal is to pregict the c lass of the mashroom , given some features of the mashroom. 
- we will use naive bayes model for this classification


In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("mushrooms.csv")
df.shape

(8124, 23)

### Encode the categorial data into Numerical Data

In [13]:
le = LabelEncoder()

# applies Transformation on each column
# apply method apply the function to each column by default 
# if you change the axis to 1 it will apply to each row

ds = df.apply(le.fit_transform)

In [14]:
ds.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment   
0      1          5            2          4        1     6                1  \
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring   
0             0          1           4  ...                         2  \
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color   
0                       7                       7          0           2  \
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [22]:
data = ds.values
print(data[:5, :])
x_data = data[:, 1:]
y_data = data[:, :1]
print(x_data.shape, y_data.shape)

[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]
(8124, 22) (8124, 1)


In [23]:
  # break the data into train and test part
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data)

In [27]:
y_train.shape

(6093, 1)

In [28]:
np.unique(y_train)

array([0, 1])

# Building the Classifier

In [36]:
a = np.array([0,0,0,1,1,0,0,1,1,0])
# simple and faster way to count the occurence of any value in np.array 
# is by using sum function and numpy shortcut
print(np.sum(a==1))
print(np.sum(a==0))


4
6


In [35]:
def prior_prob(y_train, label):
    tot_example = y_train.shape[0]
    class_example = np.sum(y_train == label)

    return (class_example)/float(tot_example)

In [37]:
#prior_prob(a, 1)

0.4

In [105]:
arr = y_train == 0
arr = arr.reshape(-1)
print(arr.shape)

x_train[arr]
print(x)

(6093,)
[False False False ... False False  True]


In [106]:
def cond_prob(x_train,y_train, feature_col, feature_val, label):
    fil_cond = y_train == label
    fil_cond = fil_cond.reshape(-1)
    x_filtered = x_train[fil_cond]
    numerator = np.sum(x_filtered[:,feature_col]== feature_val)
    denominator = np.sum(y_train == label)
    #denominator = x_filtered.shape[0]

    return numerator/ float(denominator)

### Compute posterial prob for each test example and make prediction

In [107]:
def predict(x_train, y_train, xtest):
          
     """xtest is  a single testing point with n features"""
     classes = np.unique(y_train)
     n_features = x_train.shape[1]
     # Compute Posterior for each class
     post_probs= []# list of prob for all classes and given a single testing point

     for label in classes:
          likelihood = 1.0 
          for f in range(n_features):
               cond = cond_prob(x_train,y_train, f, xtest[f],label)
               likelihood *= cond
          prior = prior_prob(y_train, label)
          post = likelihood*prior
          post_probs.append(post)
     pred = np.argmax(post_probs)

     return pred

In [110]:
predict(x_train, y_train, x_test[1])

0

In [115]:
print(y_test[1])

[0]


In [179]:
def score(x_train,x_test,y_train,y_test):
    pred = []
    for i in range(x_test.shape[0]):
        pred_label = predict(x_train, y_train, x_test[i])
        pred.append(pred_label)


    pred = np.array(pred)
    
    pred = pred.reshape(-1,1)
    
    accuracy = (np.sum(pred == y_test)/y_test.shape[0])

    return accuracy


In [180]:
score(x_train, x_test, y_train, y_test)

0.9985228951255539